name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - run: yarn
      - run: yarn build
